### ISSUE TITLE
Compiled .dll size

### ISSUE THREAD

**Issue by True-XyZ** [xieyubo/WSL2#1]
Hi. 
I have compiled computecore.dll with size of 221kb but same file in my system32 is 877kb.
If I replace old dll with compiled one wsl doesn't start.
Is something wrong?

PS. I don't have WSL folder in C:\Program Files and if I create it and put compiled dll here - nothing changes in terms of visible cores.

**Comment by xieyubo** [comment]
@True-XyZ , first, you need make sure you are using WSL2. The second, you can't replace the `computecore.dll` under system32. The binary you built is just a "proxy of the system computecore.dll", it requires the system computecore.dll to work. The third, if you don't have WSL folder under C:\Program Files, then you need find out where is `wslservice.exe`. You can open the task manager, find out the `wslservice.exe` process, right click and select `Properties` menu item.  And put the coputecore.dll you compiled into that folder.

**Comment by True-XyZ** [comment]
Thanks!
In my case folder of "wslservice.exe" is "C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe"
But I can't write here for some reason despite I've take ownership of this folder and granted full access.

**Comment by xieyubo** [comment]
Seems you install WSL windows store version. There are some ways to get the permission to update the windows store files if you search on the internet. Or you might can uninstall it and install WSL from "Control Panel -> Turn Windows features on or off -> Windows Subsystem for Linux"

**Comment by True-XyZ** [comment]
I'm sorry for my stupidity but in case if I remove WSL windows store version "wslservice.exe" is nowhere to be found, where do I put compiled dll then :) ?
"C:\Program Files\WSL" still doesn't exist but WSL forks fine (from system32).

**Comment by True-XyZ** [comment]
So...
I've modified msi installer of win store version WSL. It installs now in Program Files and also copies compiled dll in that folder.
All works fine now :)
