### ISSUE TITLE
Where is  computecore.h?

### ISSUE THREAD

**Issue by luzhiyuann** [xieyubo/WSL2#3]
The compilation outputs a fatal error: computecore.h: No such file or directory

Where can I find this file or how to generate such a file? Thanks！

**Comment by xieyubo** [comment]
That file exists in windows sdk. You can install it from the visual studio installer.

![image](https://github.com/xieyubo/WSL2/assets/147673292/969a95ac-e1df-4ccd-94bf-13995fe616dd)
